name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # Or your default branch if it's different, e.g., master
  # You can also trigger on pull requests, releases, etc.
  # pull_request:
  #   branches:
  #     - main

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME will be dynamically constructed, e.g., ghcr.io/your-username/your-repo-name
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically available

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # Construct full image path here
          tags: |
            type=sha # Creates a tag with the commit SHA
            type=raw,value=latest,enable={{is_default_branch}} # Tags 'latest' on default branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
