name: Build and Push Docker Images

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    strategy:
      matrix:
        variant:
          - name: "risu_server"
            dockerfile: "Dockerfile"
            suffix: ""
          - name: "risu_server_cloudron"
            dockerfile: "Dockerfile.cloudron"
            suffix: "_cloudron"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically available

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}${{ matrix.variant.suffix }}
          tags: |
            type=sha # Creates a tag with the commit SHA
            type=raw,value=latest,enable={{is_default_branch}} # Tags 'latest' on default branch

      - name: Build and push Docker image (${{ matrix.variant.name }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.variant.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
